test_blog:
    resource: "@testBlogBundle/Resources/config/routing.yml"
    prefix:   /test_blog

PortfolioPortfolioBundle:
    resource: "@PortfolioPortfolioBundle/Resources/config/routing.yml"
    prefix:   /
login:
    pattern:   /login
    defaults:  { _controller: PortfolioUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout