Portfolio:
    path:     /
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:index }
AddArticle:
    path:     /addArticle
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:addArticle }
Articles:
    path:     /articles
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:articles }
Studies:
    path:     /studies
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:studies }
Users:
    path:     /users
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:users }
Contact:
    path:     /contact
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:contact }
Admin:
    path:     /admin
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:admin }
Chat:
    path:     /chat
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:chat }
Account:
    path:     /account
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:account }
Article:
    path:     /article/{id}
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:article }
User:
    path:     /user/{id}
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:user }
addComment:
    path:     /addComment
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:addComment }
getComments:
    path:     /getComments/{id}
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:getComments }
removeArticle:
    path:     /removeArticle/{id}
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:removeArticle }