Portfolio:
    path:     /
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:index }
AddArticle:
    path:     /addArticle
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:addArticle }
Articles:
    path:     /articles
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:articles }
Studies:
    path:     /studies
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:studies }
Contact:
    path:     /contact
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:contact }
Admin:
    path:     /admin
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:admin }
Article:
    path:     /article/{id}
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:article }
addComment:
    path:     /addComment
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:addComment }
getComments:
    path:     /getComments/{id}
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:getComments }
removeArticle:
    path:     /removeArticle/{id}
    defaults: { _controller: PortfolioPortfolioBundle:Portfolio:removeArticle }